server:
    context-path: ''
spring:
    autoconfigure:
        exclude: ''
    datasource:
        password: ''
        username: sa
        url: jdbc:h2:~/h2/chat1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
hibernate:
    dialect: org.hibernate.dialect.H2Dialect

