chat1:
    messages:
        repository:
            maxresults: 50
hibernate:
    ejb:
        entitymanager_factory_name: ${spring.config.name}
logging:
    level:
        com:
            netflix: warn
            netflix.config.sources.URLConfigurationSource: error
            net128.app.chat1: warn
            net128.app.chat1.config:
                http: trace
                PropertiesDumper: debug
            net128.app.chat1.servlet: debug
            net128.app.chat1.Chat1Application: warn
            zaxxer.hikari.HikariDataSource: warn
        org:
            apache:
                catalina: warn
            hibernate: warn
            hibernate.type.descriptor.sql: warn
            springframework: warn
            springframework.jmx.export.annotation.AnnotationMBeanExporter: error
            springframework.beans.factory.support.DisposableBeanAdapter: error
            springframework.boot:
                context.embedded.tomcat.TomcatEmbeddedServletContainer: info
                web.embedded.undertow: info
                web.embedded.tomcat: info
                web.embedded.jetty: info
            reflections: warn
        springfox: warn
server:
#    max-http-post-size: 104857600
    maxPostSize: 104857600
    servlet:
        context-path: ''
spring:
    application:
        name: chat1
    config:
        name: ${spring.application.name}
    hateoas:
        use-hal-as-default-json-media-type: false
    h2.console.enabled: false
    Multipart: &multipart
        max-file-size: '${server.maxPostSize}'
        max-request-size: '${spring.Multipart.max-file-size}'
    http:
        <<: *multipart
    servlet:
        <<: *multipart
    jackson:
        default-property-inclusion: non_null
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
            fail-on-empty-beans: false
    jpa:
        open-in-view: false
    output:
        ansi:
            enabled: detect
    autoconfigure:
        exclude: >
            org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
            org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,
            org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management.endpoints.enabled-by-default: true
management.endpoints.web.exposure.include: '*'
open:
    endpoint:
        uris: /hrrs, /hrrs/**, /actuator/**

