server:
    port: 20090
spring:
    autoconfigure:
        exclude: ''
    datasource:
        password: ''
        username: sa
        url: jdbc:h2:mem:chat1-perftest;MODE=MySQL;DB_CLOSE_ON_EXIT=TRUE
#        url: jdbc:h2:~/h2/chat1-perftest;MODE=MySQL;DB_CLOSE_ON_EXIT=TRUE
    jpa.hibernate.ddl-auto: create-drop
hibernate:
    dialect: org.hibernate.dialect.H2Dialect
chat1:
    userconfig:
        users:
        -   name: user
            password: password
            role: USER